// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!
// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!
// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!

package gen

type UserCreate struct {
  CreatedAt string
  UpdatedAt string
  PromotedAt *string
}

type UserCreateConstructor struct {
  CreatedAt string
  UpdatedAt string
  PromotedAt *string
}
