// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!

export type Activity = {
  id: string;
  createdAt: string;
};

export type FullName = {
  firstName: string;
  lastName: string;
};

export enum NumberEnum {
  VIEW = 0,
  EDIT = 1,
  CREATE = 2,
}

export enum PermissionsEnum {
  VIEW = 'view',
  EDIT = 'edit',
  CREATE_EXTRA_SUPER_FILE = 'create-extra-super-file',
}

export type Profile = {
  name: FullName | null;
  age: number;
};

export type User = {
  id: string;
  bestFriend: User | null;
  friends: User[];
  selfProperty: User;
  selfConstructor: User;
};

export type UserCreate = {
  id: string;
  permissions: PermissionsEnum;
  profile: Profile | null;
  age: number;
  name: string | null;
  latitude: number;
  longitude: number;
  achievements: any[];
  tags: string[];
  activities: Activity[];
  mixed: any;
  isApproved: boolean | null;
};
