<?php

declare(strict_types=1);

namespace Riverwaysoft\DtoConverter\OutputWriter\OutputProcessor;

use Riverwaysoft\DtoConverter\OutputWriter\OutputFile;

class PrependAutogeneratedNoticeFileProcessor implements SingleOutputFileProcessorInterface
{
    public function __construct(private string $text = "// THE FILE WAS AUTOGENERATED USING DTO-CONVERTER. PLEASE DO NOT EDIT IT!\n\n")
    {
    }

    public function process(OutputFile $outputFile): OutputFile
    {
        return new OutputFile(
            relativeName: $outputFile->getRelativeName(),
            content: $this->text . $outputFile->getContent(),
        );
    }
}
