// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!
// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!
// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!

package gen

type CloudNotify struct {
  Id string
  FcmToken *string
}

type Response struct {
  Data any
}

type UserCreate struct {
  Achievements []string
  Matrix [][]int
  Name *string
  DuplicatesInType any
  Age any
  IsApproved *bool
  Latitude float64
  Longitude float64
  Mixed any
}
