// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!
// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!
// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!

package gen

type CloudNotify struct {
	Id       string  `json:"id"`
	FcmToken *string `json:"fcmToken"`
}

type Response struct {
	Data interface{} `json:"data"`
}

type UserCreate struct {
	Achievements     []string    `json:"achievements"`
	Matrix           [][]int     `json:"matrix"`
	Name             *string     `json:"name"`
	DuplicatesInType *string     `json:"duplicatesInType"`
	Age              int         `json:"age"`
	IsApproved       *bool       `json:"isApproved"`
	Latitude         float64     `json:"latitude"`
	Longitude        float64     `json:"longitude"`
	Mixed            interface{} `json:"mixed"`
}
