// THE FILE WAS AUTOGENERATED USING DTO-CONVERTER. PLEASE DO NOT EDIT IT!

export type UserCreate = {
  createdAt: string;
  updatedAt: string;
  promotedAt: string | null;
};

export type UserCreateConstructor = {
  createdAt: string;
  updatedAt: string;
  promotedAt: string | null;
};
