// THE FILE WAS AUTOGENERATED USING DTO-CONVERTER. PLEASE DO NOT EDIT IT!

import axios from 'axios';

export type AdminZoneChatCreateInput = {
  id: string;
  isAdmin: boolean;
};

export type AdminZoneChatOutput = {
  id: string;
  isAdmin: boolean;
};

export type ChatOutput = {
  id: string;
};

export const apiChatsGet = (): Promise<ChatOutput> => {
  return axios
    .get<ChatOutput>(`/api/chats`)
    .then((response) => response.data);
}

export const apiChatsAdminZoneGet = (): Promise<AdminZoneChatOutput> => {
  return axios
    .get<AdminZoneChatOutput>(`/api/chats_admin_zone`)
    .then((response) => response.data);
}

export const apiChatsAdminZonePost = (body: AdminZoneChatCreateInput): Promise<AdminZoneChatOutput> => {
  return axios
    .post<AdminZoneChatOutput>(`/api/chats_admin_zone`, body)
    .then((response) => response.data);
}
