// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!

import axios from 'axios';

export type JsonResponse<T> = {
  data: T;
};

export type UserOutput = {
  id: string;
};

export const apiRouteWithAnnotationsReturnGet = (): Promise<UserOutput> => {
  return axios
    .get<UserOutput>(`/api/route-with-annotations-return`)
    .then((response) => response.data);
}

export type CollectionResponse<Resource extends {id: string}> = {
  'hydra:member': Resource[];
  'hydra:totalItems': number;
  'hydra:view': { '@id': string; 'hydra:last': string };
  'hydra:search': { 'hydra:mapping': any[] };
  'hydra:last': string;
};