// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!

import axios from 'axios';

export type CreateUserInput = {
  id: string;
};

export type FilterQuery = {
  age: number | null;
  name: string | null;
};

export type UpdateUserInput = {
  id: string;
};

export type UserOutput = {
  id: string;
};

export const apiRouteWithAnnotationsReturnGet = (): Promise<UserOutput> => {
  return axios
    .get<UserOutput>(`/api/route-with-annotations-return`)
    .then((response) => response.data);
}

export const apiRouteWithNameGet = (): Promise<null> => {
  return axios
    .get<null>(`/api/route-with-name`)
    .then((response) => response.data);
}

export const apiRouteWithPathGet = (): Promise<null> => {
  return axios
    .get<null>(`/api/route-with-path`)
    .then((response) => response.data);
}

export const apiUsersGet = (): Promise<UserOutput[]> => {
  return axios
    .get<UserOutput[]>(`/api/users`)
    .then((response) => response.data);
}

export const apiUsersPost = (input: CreateUserInput): Promise<UserOutput> => {
  return axios
    .post<UserOutput>(`/api/users`, input)
    .then((response) => response.data);
}

export const apiUsersWithFiltersGet = (query: FilterQuery): Promise<UserOutput[]> => {
  return axios
    .get<UserOutput[]>(`/api/users-with-filters`, { params: query })
    .then((response) => response.data);
}

export const apiUsersUserGet = (user: string): Promise<UserOutput> => {
  return axios
    .get<UserOutput>(`/api/users/${user}`)
    .then((response) => response.data);
}

export const apiUsersUpdateItUserToUpdatePut = (userToUpdate: string, input: UpdateUserInput): Promise<UserOutput> => {
  return axios
    .put<UserOutput>(`/api/users_update-it/${userToUpdate}`, input)
    .then((response) => response.data);
}

export type CollectionResponse<Resource extends {id: string}> = {
  'hydra:member': Resource[];
  'hydra:totalItems': number;
  'hydra:view': { '@id': string; 'hydra:last': string };
  'hydra:search': { 'hydra:mapping': any[] };
  'hydra:last': string;
};