// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!

export type ColorEnum = 0 | 1 | 2;

export type RoleEnum = 'admin' | 'reader' | 'editor';

export type User = {
  id: string;
  themeColor: ColorEnum;
  role: RoleEnum;
};
