// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!

export enum Color {
  RED = 0,
  BLUE = 1,
  WHITE = 2,
}

export enum Role {
  ADMIN = 'admin',
  EDITOR = 'editor',
  READER = 'reader',
}

export type User = {
  color: Color;
  role: Role;
};
