// Code generated by php-converter. DO NOT EDIT.
// Code generated by php-converter. DO NOT EDIT.
// Code generated by php-converter. DO NOT EDIT.

package gen

type A struct {
	CreatedAt string `json:"createdAt"`
}

type GenderEnum int

const (
	UNKNOWN GenderEnum = 2
	MAN     GenderEnum = 0
	WOMAN   GenderEnum = 1
)
