// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!
// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!
// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!

package gen

type Activity struct {
	Id        string
	CreatedAt string
}

type FullName struct {
	FirstName string
	LastName  string
}

type NumberEnum int

const (
	VIEW   NumberEnum = 0
	EDIT   NumberEnum = 1
	CREATE NumberEnum = 2
)

type PermissionsEnum string

const (
	VIEWPermissionsEnum PermissionsEnum = "view"
	EDITPermissionsEnum PermissionsEnum = "edit"
)

type Profile struct {
	Name *FullName
	Age  int
}

type User struct {
	Id              string
	BestFriend      *User
	Friends         []User
	SelfProperty    *User
	SelfConstructor *User
}

type UserCreate struct {
	Id           string
	Permissions  PermissionsEnum
	Profile      *Profile
	Age          int
	Name         *string
	Latitude     float64
	Longitude    float64
	Achievements []interface{}
	Tags         []string
	Activities   []Activity
	Mixed        interface{}
	IsApproved   *bool
}
