// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!
// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!
// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!

package gen

type Activity struct {
	Id        string `json:"id"`
	CreatedAt string `json:"createdAt"`
}

type FullName struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type NumberEnum int

const (
	VIEW   NumberEnum = 0
	EDIT   NumberEnum = 1
	CREATE NumberEnum = 2
)

type PermissionsEnum string

const (
	VIEWPermissionsEnum PermissionsEnum = "view"
	EDITPermissionsEnum PermissionsEnum = "edit"
)

type Profile struct {
	Name *FullName `json:"name"`
	Age  int       `json:"age"`
}

type User struct {
	Id              string `json:"id"`
	BestFriend      *User  `json:"bestFriend"`
	Friends         []User `json:"friends"`
	SelfProperty    *User  `json:"selfProperty"`
	SelfConstructor *User  `json:"selfConstructor"`
}

type UserCreate struct {
	Id           string          `json:"id"`
	Permissions  PermissionsEnum `json:"permissions"`
	Profile      *Profile        `json:"profile"`
	Age          int             `json:"age"`
	Name         *string         `json:"name"`
	Latitude     float64         `json:"latitude"`
	Longitude    float64         `json:"longitude"`
	Achievements []interface{}   `json:"achievements"`
	Tags         []string        `json:"tags"`
	Activities   []Activity      `json:"activities"`
	Mixed        interface{}     `json:"mixed"`
	IsApproved   *bool           `json:"isApproved"`
}
