// Code generated by php-converter. DO NOT EDIT.
// Code generated by php-converter. DO NOT EDIT.
// Code generated by php-converter. DO NOT EDIT.

package gen

type UserCreate struct {
	CreatedAt  string  `json:"createdAt"`
	UpdatedAt  string  `json:"updatedAt"`
	PromotedAt *string `json:"promotedAt"`
}

type UserCreateConstructor struct {
	CreatedAt  string  `json:"createdAt"`
	UpdatedAt  string  `json:"updatedAt"`
	PromotedAt *string `json:"promotedAt"`
}
