// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!
// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!
// THE FILE WAS AUTOGENERATED USING PHP-CONVERTER. PLEASE DO NOT EDIT IT!

package gen

type FullName struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Me struct {
	Request *UserCreate `json:"request"`
}

type Profile struct {
	Name *FullName `json:"name"`
	Age  int       `json:"age"`
}

type UserCreate struct {
	Id      string   `json:"id"`
	Profile *Profile `json:"profile"`
	Me      *Me      `json:"me"`
}
